# Spring Boot Application Properties

# Server Configuration
server.port=${PORT:9090}
server.servlet.context-path=/

# Application Name
spring.application.name=Hotel Scraper API

# Logging Configuration
logging.level.root=INFO
logging.level.com.hotelapi=INFO
logging.level.scraper=INFO

# Request timeout
server.tomcat.connection-timeout=30000

# Static Resources Configuration
spring.web.resources.static-locations=file:frontend/,classpath:/static/,classpath:/public/,classpath:/resources/,classpath:/META-INF/resources/
